### ISSUE TITLE
Bulk creation of enums from YAML file?

### ISSUE THREAD

**Issue by jdunwoody** [mdub/another_enum#1]
We are using another_enum (at Hooroo) and in one case we have ~300 enums in one file. We refactored this example to initialise itself from a YAML file. Would you like to see this type of initialisation in your gem? I could work on a pull request that takes a YAML file and creates a bunch of enums from that?

**Comment by mdub** [comment]
Hi James. 

I'd be curious to see an example of the YAML file.  But my gut feel is that, no, this doesn't sound like it should belong in the gem.

**Comment by jdunwoody** [comment]
No problem. The solution was quite simple and wouldn't be difficult for a user of the gem to craft themselves if they needed it.
James
